views:
  source.toolkit.fluxcd.io/v1/gitrepositories: &gitrepos
    columns:
      - NAMESPACE
      - NAME
      - SUSPEND:.spec.suspend
      - READY

  source.toolkit.fluxcd.io/v1beta2/gitrepositories: *gitrepos

  kustomize.toolkit.fluxcd.io/v1/kustomizations: &kustomizations
    columns:
      - NAMESPACE
      - NAME
      - SUSPEND:.spec.suspend

  kustomize.toolkit.fluxcd.io/v1beta2/kustomizations: *kustomizations
